/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchant/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merchant Predict */
        post: operations["merchant_predict_api_v1_merchant_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchant/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Merchant Cities */
        get: operations["merchant_cities_api_v1_merchant_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchant/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Merchant Categories */
        get: operations["merchant_categories_api_v1_merchant_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchant/categories/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve merchant business type text to cat_* keys */
        get: operations["merchant_categories_resolve_api_v1_merchant_categories_resolve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchant/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Merchant Coverage */
        get: operations["merchant_coverage_api_v1_merchant_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List States */
        get: operations["list_states_api_v1_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search V1 */
        post: operations["search_v1_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
            /** Repo Root */
            repo_root: string;
            /** Spatial Csv */
            spatial_csv: boolean;
            /** Survival Pkl */
            survival_pkl: boolean;
            /** Rating Pkl */
            rating_pkl: boolean;
            /** Retrieval Business Csv */
            retrieval_business_csv: boolean;
            /** Retrieval Index */
            retrieval_index: boolean;
        };
        /** MerchantPredictRequest */
        MerchantPredictRequest: {
            /**
             * City
             * @description 过滤参考商户；为空则取表头前 N 行
             */
            city?: string | null;
            /**
             * State
             * @description Optional USPS state to disambiguate duplicate city names
             */
            state?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Category Keys
             * @description train_spatial cat_*; optional if category_query is set
             * @default []
             */
            category_keys: string[];
            /**
             * Category Query
             * @description Plain text, e.g. 'burger, coffee' — server resolves to cat_* for the slice
             */
            category_query?: string | null;
            /**
             * Max Rows If No City
             * @default 2000
             */
            max_rows_if_no_city: number;
        };
        /** MerchantPredictResponse */
        MerchantPredictResponse: {
            /**
             * Resolved Category Keys
             * @default []
             */
            resolved_category_keys: string[];
            /** Survival Probability */
            survival_probability: number;
            /** Predicted Stars */
            predicted_stars: number;
            /** Reference Row Count */
            reference_row_count: number;
            /** City Filter */
            city_filter?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Live Feature Preview */
            live_feature_preview?: {
                [key: string]: number;
            };
            /** Inside Reference Hull */
            inside_reference_hull: boolean;
        };
        /** MerchantCoverageResponse */
        MerchantCoverageResponse: {
            /** City Filter */
            city_filter?: string | null;
            /** Reference Count */
            reference_count: number;
            /** Geo Count */
            geo_count: number;
            /** Min Lon */
            min_lon: number;
            /** Min Lat */
            min_lat: number;
            /** Max Lon */
            max_lon: number;
            /** Max Lat */
            max_lat: number;
            /** Center Lon */
            center_lon: number;
            /** Center Lat */
            center_lat: number;
            /** Hull Geojson */
            hull_geojson?: Record<string, never> | null;
            /** Sample Points Geojson */
            sample_points_geojson?: Record<string, never> | null;
            /** Valid Hull */
            valid_hull: boolean;
        };
        /** MerchantCityRow */
        MerchantCityRow: {
            /** City */
            city: string;
            /**
             * State
             * @default
             */
            state: string;
            /** Row Count */
            row_count: number;
            /** Center Lat */
            center_lat: number;
            /** Center Lon */
            center_lon: number;
        };
        /** MerchantCitiesResponse */
        MerchantCitiesResponse: {
            /** Cities */
            cities: components["schemas"]["MerchantCityRow"][];
        };
        /** MerchantCategoriesResponse */
        MerchantCategoriesResponse: {
            /** Category Keys */
            category_keys: string[];
        };
        /**
         * SearchRequest
         * @description 与前端 `/search`（Step1–2 与侧栏权重）对齐的检索请求字段。
         */
        SearchRequest: {
            /**
             * Query
             * @description Step2 自然语言；discover_only 时可空
             * @default
             */
            query: string;
            /**
             * State
             * @description USPS 州码
             */
            state: string;
            /**
             * City
             * @description 可选城市名（精确匹配）
             */
            city?: string | null;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /**
             * Pool K
             * @description 内部候选池 Top-N（前端默认 45）
             */
            pool_k?: number | null;
            /**
             * Keywords Extra
             * @description 额外关键词
             */
            keywords_extra?: string | null;
            /**
             * Force Rebuild Index
             * @default false
             */
            force_rebuild_index: boolean;
            /**
             * Discover Only
             * @description True = 「Find general restaurants here」
             * @default false
             */
            discover_only: boolean;
            /**
             * Cuisines
             * @description 菜系多选：Sushi, Steakhouse, Korean, …
             */
            cuisines?: string[];
            /**
             * W Semantic
             * @default 0.85
             */
            w_semantic: number;
            /**
             * W Rating
             * @default 1.05
             */
            w_rating: number;
            /**
             * W Price
             * @default 0.15
             */
            w_price: number;
            /**
             * W Distance
             * @default 0.2
             */
            w_distance: number;
            /**
             * W Popularity
             * @default 0.1
             */
            w_popularity: number;
            /** Liked Business Ids */
            liked_business_ids?: string[];
            /** Disliked Business Ids */
            disliked_business_ids?: string[];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
        };
        /** StatesResponse */
        StatesResponse: {
            /** States */
            states: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    merchant_predict_api_v1_merchant_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantPredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantPredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merchant_cities_api_v1_merchant_cities_get: {
        parameters: {
            query?: {
                min_rows?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantCitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merchant_categories_api_v1_merchant_categories_get: {
        parameters: {
            query?: {
                city?: string | null;
                state?: string | null;
                max_rows_if_no_city?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantCategoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merchant_categories_resolve_api_v1_merchant_categories_resolve_get: {
        parameters: {
            query: {
                q: string;
                city?: string | null;
                state?: string | null;
                max_rows_if_no_city?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantCategoriesResponse"];
                };
            };
            /** @description No category match */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merchant_coverage_api_v1_merchant_coverage_get: {
        parameters: {
            query?: {
                city?: string | null;
                state?: string | null;
                max_rows_if_no_city?: number;
                max_sample_points?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantCoverageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_states_api_v1_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatesResponse"];
                };
            };
        };
    };
    search_v1_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
