/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchant/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merchant Predict */
        post: operations["merchant_predict_api_v1_merchant_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List States */
        get: operations["list_states_api_v1_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search V1 */
        post: operations["search_v1_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
            /** Repo Root */
            repo_root: string;
            /** Spatial Csv */
            spatial_csv: boolean;
            /** Survival Pkl */
            survival_pkl: boolean;
            /** Rating Pkl */
            rating_pkl: boolean;
            /** Retrieval Business Csv */
            retrieval_business_csv: boolean;
            /** Retrieval Index */
            retrieval_index: boolean;
        };
        /** MerchantPredictRequest */
        MerchantPredictRequest: {
            /**
             * City
             * @description 过滤参考商户；为空则取表头前 N 行
             */
            city?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Category Keys
             * @description train_spatial 中的 cat_* 列名，如 cat_coffee_&_tea
             */
            category_keys: string[];
            /**
             * Max Rows If No City
             * @default 2000
             */
            max_rows_if_no_city: number;
        };
        /** MerchantPredictResponse */
        MerchantPredictResponse: {
            /** Survival Probability */
            survival_probability: number;
            /** Predicted Stars */
            predicted_stars: number;
            /** Reference Row Count */
            reference_row_count: number;
            /** City Filter */
            city_filter?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Live Feature Preview */
            live_feature_preview?: {
                [key: string]: number;
            };
        };
        /**
         * SearchRequest
         * @description 与前端 `/search`（Step1–2 与侧栏权重）对齐的检索请求字段。
         */
        SearchRequest: {
            /**
             * Query
             * @description Step2 自然语言；discover_only 时可空
             * @default
             */
            query: string;
            /**
             * State
             * @description USPS 州码
             */
            state: string;
            /**
             * City
             * @description 可选城市名（精确匹配）
             */
            city?: string | null;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /**
             * Pool K
             * @description 内部候选池 Top-N（前端默认 45）
             */
            pool_k?: number | null;
            /**
             * Keywords Extra
             * @description 额外关键词
             */
            keywords_extra?: string | null;
            /**
             * Force Rebuild Index
             * @default false
             */
            force_rebuild_index: boolean;
            /**
             * Discover Only
             * @description True = 「Find general restaurants here」
             * @default false
             */
            discover_only: boolean;
            /**
             * Cuisines
             * @description 菜系多选：Sushi, Steakhouse, Korean, …
             */
            cuisines?: string[];
            /**
             * W Semantic
             * @default 0.85
             */
            w_semantic: number;
            /**
             * W Rating
             * @default 1.05
             */
            w_rating: number;
            /**
             * W Price
             * @default 0.15
             */
            w_price: number;
            /**
             * W Distance
             * @default 0.2
             */
            w_distance: number;
            /**
             * W Popularity
             * @default 0.1
             */
            w_popularity: number;
            /** Liked Business Ids */
            liked_business_ids?: string[];
            /** Disliked Business Ids */
            disliked_business_ids?: string[];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
        };
        /** StatesResponse */
        StatesResponse: {
            /** States */
            states: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    merchant_predict_api_v1_merchant_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantPredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantPredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_states_api_v1_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatesResponse"];
                };
            };
        };
    };
    search_v1_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
